### ISSUE TITLE
Token Colors Missing

### ISSUE THREAD

**Issue by alextremblay** [Y-Ysss/vscode-cisco-config-highlight#1]
First off, thank you so much for making this. it looks absolutely awesome!

The problem i have is that i can't replicate any of the colors shown in your screenshot.

As an example, your screenshot appears to show that lines starting with `no` are highlighted blue.
That's not the case for me. If inspect such a line with the "Inspect Editor Tokens and Scopes" tool, as you can see in the below image, it does correctly identify the scope for the line, but has no custom foreground ("No theme selector")
![image](https://user-images.githubusercontent.com/23367954/128930960-31e54211-2d74-40d7-8ad1-9391d0414ed8.png)

Do you know why that might be, or what I can do to troubleshoot / fix this?

**Comment by alextremblay** [comment]
I've replicated the colors by using the following override in my vscode settings.json file:

```json
  "editor.tokenColorCustomizations": {
      "textMateRules": [
          {
              "scope": "meta.function-call",
              "settings": {
                  "foreground": "#6191C1",
              }
          },
          {
              "scope": "punctuation.config-param.first.cisco",
              "settings": {
                  "foreground": "#4FB3B3",
              }
          },
          {
              "scope": "meta.function-call",
              "settings": {
                  "foreground": "#6191C1",
              }
          },
      ]
  },
```

is this something that should be included in the vscode extension?

I'd be happy to submit a PR, but i've never written a vscode extension, so i'm not really sure where this data should go & what format it needs to be in

**Comment by Y-Ysss** [comment]
Thank you for using the extension. I am very happy to get a direct thanks from you.


This image shows a plain VSCode with `Cisco Config Highlight` installed and the token color customized.

Screenshot show lines starting with no are highlighted blue(foreground : #6191C1).
The only extensions installed are `Cisco Config Highlight` and the language pack.

![image](https://user-images.githubusercontent.com/10232644/129230463-ff0d759a-4b30-4566-9527-23d50c434171.png)

Please try adding the settings as shown in the image.

You can open the `settings.json` file by typing `Preferences: Open Settings (JSON)` in the command palette.

The command palette can be opened by choosing `View > Command Palette (Ctrl+Shift+P)` or shortcut key.
Default file location for Windows `C:\ Users\{USERNAME}\AppData\Roming\Code\User\settings.json` (`AppData` is hidden folder).

As a side note, the `Cisco Config Highlight` screenshot is based on the colors of the My VSCode theme(https://marketplace.visualstudio.com/items?itemName=Y-Ysss.vscode-daybreak-theme) that I have published.


If there is a mismatch between your question and my answer or if you are having problems, please reply to the Issue.

**Comment by alextremblay** [comment]
nope, that sounds great.

Does this mean that everyone who wants syntax highlighting for `meta.function-call` and `punctuation.config-param.first.cisco` needs to add custom `"editor.tokenColorCustomizations"` settings to their `settings.json` file, or is there a way to package these default colors as part of the VSCode extension?

**Comment by Y-Ysss** [comment]
The color of syntax highlighting depends on the theme you have enabled.

If the theme you currently have enabled does not define the colors, you will need to customize the `settings.json` file.

For example, the Sublime Material Theme (https://marketplace.visualstudio.com/items?itemName=jprestidge.theme-material-theme) does not require customization of the `settings.json` file, as shown in the image below.

The VSCode `settings.json` file only contains the theme activation.

![image](https://user-images.githubusercontent.com/10232644/129449425-0b27a0e5-4358-48b1-ad12-eb693a222931.png)

**Comment by alextremblay** [comment]
Ahhhh, I see, it's a problem with my theme

Ok, thank you for clarifying this :)

**Comment by Jean-Daniel** [comment]
I had the same issue with the default VSCode theme.
Maybe the readme should mention that it works better with a custom theme like "Sublime Material Theme", instead of simply stating that it depends on the actual theme.
