### ISSUE TITLE
lines prefixed with # are not highlighted

### ISSUE THREAD

**Issue by Paul-Jerome** [Y-Ysss/vscode-cisco-config-highlight#5]
Lines/ strings beginning with # should be marked as comments or annotations the same as those beginning with !

**Comment by yuyosy** [comment]
Hi @Paul-Jerome !
Thank you for using my extension!

> Lines/ strings beginning with # should be marked as comments or annotations the same as those beginning with !

Thanks for reminding me.

I will add it to the regular expression pattern to be marked as a comment.
If this pattern is matched, it is highlighted as a comment, like a line beginning with an exclamation mark.

```
^\s*[!#].*
```


![image](https://user-images.githubusercontent.com/10232644/174439833-40edc38e-af29-4fea-a909-696b756926fc.png)


If I add the above pattern, the changes will be included in the next release.

If there is a mismatch between your request and my answer or if you are having more requests, please reply to the Issue.

**Comment by Paul-Jerome** [comment]
Fantastic. 
Look forward to the update!  (I work on IOS-XR a lot and policy comments use # so this will make me very happy)

**Comment by yuyosy** [comment]
@Paul-Jerome 

A new version has been released with the above pattern added.
Features are now available! 🎉 

Thank you for the Issue.

I do not use IOS-XR in my business. Please continue to create Issue if you find any improvements in daily use.

---

🕙 Updated : 2022-06-21
✅ Release : [v0.5.0](https://github.com/Y-Ysss/vscode-cisco-config-highlight/releases/tag/v0.5.0)
📜 Changelog : https://github.com/Y-Ysss/vscode-cisco-config-highlight/blob/main/CHANGELOG.md#050-2022-06-21
